In [1]:
import torch

In [2]:
A= torch.FloatTensor([[[1,2],[3,4],[5,6],[7,8]], [[9,10],[11,12],[13,14],[15,16]], [[17,18],[19,20],[21,22],[23,24]]])

In [3]:
A = torch.stack((A, 2*A))

In [4]:
A.size()

torch.Size([2, 3, 4, 2])

In [5]:
tmp = torch.tensor([2,0,1])
P = torch.eye(3)
P = P[tmp]
P

tensor([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]])

In [7]:
P.T

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [6]:
X = torch.arange(9).reshape(3,3).type(torch.FloatTensor)
X@(P.T)

tensor([[2., 0., 1.],
        [5., 3., 4.],
        [8., 6., 7.]])

In [8]:
torch.einsum('jk..., ik -> ji...', X, P)

tensor([[2., 0., 1.],
        [5., 3., 4.],
        [8., 6., 7.]])

In [9]:
A.flatten(start_dim=1).shape

torch.Size([2, 24])

In [10]:
B = torch.einsum('jk..., ik -> ji...', A, P)

In [11]:
B.flatten(start_dim=1)

tensor([[17., 18., 19., 20., 21., 22., 23., 24.,  1.,  2.,  3.,  4.,  5.,  6.,
          7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
        [34., 36., 38., 40., 42., 44., 46., 48.,  2.,  4.,  6.,  8., 10., 12.,
         14., 16., 18., 20., 22., 24., 26., 28., 30., 32.]])

In [39]:
torch.einsum(
                    "jk..., ki -> ji...",
                    A.flatten(start_dim=1),
                    torch.kron(P.T.contiguous(),torch.eye(8)),
                )

tensor([[17., 18., 19., 20., 21., 22., 23., 24.,  1.,  2.,  3.,  4.,  5.,  6.,
          7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
        [34., 36., 38., 40., 42., 44., 46., 48.,  2.,  4.,  6.,  8., 10., 12.,
         14., 16., 18., 20., 22., 24., 26., 28., 30., 32.]])

In [44]:
torch.block_diag(P,P,P,P,P,P,P,P).shape

torch.Size([24, 24])

In [37]:
P.T

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [48]:
for k in P.T:
    for j in 

tensor([0., 1., 0.])
tensor([0., 0., 1.])
tensor([1., 0., 0.])
