In [1]:
import torch

In [2]:
A= torch.FloatTensor([[[1,2],[3,4],[5,6],[7,8]], [[9,10],[11,12],[13,14],[15,16]], [[17,18],[19,20],[21,22],[23,24]]])

In [3]:
A = torch.stack((A, 2*A))

In [5]:
A = torch.einsum('ijkl -> jikl', A)

In [9]:
A

tensor([[[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.],
          [ 7.,  8.]],

         [[ 2.,  4.],
          [ 6.,  8.],
          [10., 12.],
          [14., 16.]]],


        [[[ 9., 10.],
          [11., 12.],
          [13., 14.],
          [15., 16.]],

         [[18., 20.],
          [22., 24.],
          [26., 28.],
          [30., 32.]]],


        [[[17., 18.],
          [19., 20.],
          [21., 22.],
          [23., 24.]],

         [[34., 36.],
          [38., 40.],
          [42., 44.],
          [46., 48.]]]])

In [10]:
tmp = torch.tensor([2,0,1])
P = torch.eye(3)
P = P[tmp]
P

tensor([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]])

In [11]:
torch.einsum('ij, j... -> i...', P,A)

tensor([[[[17., 18.],
          [19., 20.],
          [21., 22.],
          [23., 24.]],

         [[34., 36.],
          [38., 40.],
          [42., 44.],
          [46., 48.]]],


        [[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.],
          [ 7.,  8.]],

         [[ 2.,  4.],
          [ 6.,  8.],
          [10., 12.],
          [14., 16.]]],


        [[[ 9., 10.],
          [11., 12.],
          [13., 14.],
          [15., 16.]],

         [[18., 20.],
          [22., 24.],
          [26., 28.],
          [30., 32.]]]])

In [16]:
A[:,0,0,0]

tensor([ 1.,  9., 17.])

In [20]:
torch.einsum('ij, j...-> i...', P,A[:,0,0,0])

tensor([17.,  1.,  9.])

In [10]:
B = torch.einsum('jk..., ik -> ji...', A, P)

In [11]:
B.flatten(start_dim=1)

tensor([[17., 18., 19., 20., 21., 22., 23., 24.,  1.,  2.,  3.,  4.,  5.,  6.,
          7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
        [34., 36., 38., 40., 42., 44., 46., 48.,  2.,  4.,  6.,  8., 10., 12.,
         14., 16., 18., 20., 22., 24., 26., 28., 30., 32.]])

In [39]:
torch.einsum(
                    "jk..., ki -> ji...",
                    A.flatten(start_dim=1),
                    torch.kron(P.T.contiguous(),torch.eye(8)),
                )

tensor([[17., 18., 19., 20., 21., 22., 23., 24.,  1.,  2.,  3.,  4.,  5.,  6.,
          7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
        [34., 36., 38., 40., 42., 44., 46., 48.,  2.,  4.,  6.,  8., 10., 12.,
         14., 16., 18., 20., 22., 24., 26., 28., 30., 32.]])

In [44]:
torch.block_diag(P,P,P,P,P,P,P,P).shape

torch.Size([24, 24])

In [37]:
P.T

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [48]:
for k in P.T:
    for j in 

tensor([0., 1., 0.])
tensor([0., 0., 1.])
tensor([1., 0., 0.])
